# ==============================
# Owner-Service (??????????? ??????????)
# ==============================

# 1) H2 in-memory DB
spring.datasource.url=jdbc:h2:mem:ownerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ (?????????? ??? ?? RabbitMQ, ??? ? Gateway)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ???? ?????????? (????? ?? ????????????? ? Gateway/other)
server.port=8081
