name: Java CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Make Gradle wrapper executable
        run: chmod +x lab3/gradlew

      - name: Validate Gradle wrapper
        run: cd lab3 && ./gradlew wrapperValidation

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build with Gradle
        run: cd lab3 && ./gradlew build
